INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Major,15','Tarragona','Oscars','43100');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Avinguda dels Pins,5','Reus','Jack','43206');

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Carrer dels plàtans,20','Cambrils','Nemo','43205');