@startuml
left to right direction

actor Admin
actor Gestor
actor Client

rectangle "Cinema App"{
  Admin -- (Gestionar Cinemes)
  Admin -- (Gestionar Sales)
  Admin -- (Gestionar Seients)

  Gestor -- (Gestionar Screenings)
  Gestor -- (Gestionar Pel·licules)
}
@enduml